
public class main {
    public static void main(String[] args) {
        System.out.println("------------Bus-----------");
        Bus bus1 = new Bus();
        Bus bus2 = new Bus();
        System.out.println("----------------------------");
        System.out.println(bus1.num);
        System.out.println(bus2.num);
        System.out.println("--------------1번------------");
        bus1.boarding(2);
        System.out.println("--------------2번------------");
        System.out.println(bus1.currentPassenger);
        System.out.println(bus1.possiblePassenger);
        System.out.println(bus1.payCheck);
        System.out.println("--------------3번------------");
        bus1.setOil(-50);
        System.out.println("--------------4번------------");
        System.out.println(bus1.oil);
        System.out.println("--------------5번------------");
        bus1.busStatusChange("차고지행");
        System.out.println("--------------6번------------");
        bus1.setOil(10);
        System.out.println("--------------7번------------");
        System.out.println(bus1.status);
        System.out.println(bus1.oil);
        System.out.println("--------------8번------------");
        bus1.driveStart();
        System.out.println("--------------9번,10번------------");
        bus1.boarding(45);
        System.out.println("--------------11번------------");
        bus1.boarding(5);
        System.out.println("--------------12번------------");
        System.out.println(bus1.currentPassenger);
        System.out.println(bus1.possiblePassenger);
        System.out.println(bus1.payCheck);
        System.out.println("--------------13번------------");
        bus1.setOil(-55);
        System.out.println("--------------14,15번------------");
        System.out.println(bus1.oil);
        bus1.statusChecking();
        System.out.println(bus1.status);

        System.out.println("------------Taxi-----------");
        Taxi taxi1 = new Taxi();
        Taxi taxi2 = new Taxi();
        System.out.println("----------------------------");
        System.out.println(taxi1.num);
        System.out.println(taxi2.num);
        System.out.println(taxi1.oil);
        System.out.println(taxi2.oil);
        System.out.println(taxi1.status);
        System.out.println(taxi2.status);
        System.out.println("--------------1번------------");
        taxi1.boarding(2);
        taxi1.setDestination("서울역",2);
        System.out.println("--------------2번------------");
        System.out.println(taxi1.currentPassenger);
        System.out.println(taxi1.possiblePassenger);
        System.out.println(taxi1.charge);
        System.out.println(taxi1.destination);
        System.out.println(taxi1.destinationDistance);
        taxi1.payChecking();
        System.out.println(taxi1.payCheck);
        System.out.println(taxi1.status);
        System.out.println("--------------3번------------");
        taxi1.setOil(-80);
        System.out.println("--------------4번------------");
        taxi1.charge();
        System.out.println("--------------5번------------");
        System.out.println(taxi1.oil);
        System.out.println(taxi1.money);
        System.out.println("--------------6,7번------------");
        taxi1.boarding(5);
        System.out.println("--------------8번------------");
        taxi1.boarding(3);
        taxi1.setDestination("구로디지털단지역",12);
        System.out.println("--------------9번------------");
        System.out.println(taxi1.currentPassenger);
        System.out.println(taxi1.possiblePassenger);
        System.out.println(taxi1.charge);
        System.out.println(taxi1.destination);
        System.out.println(taxi1.destinationDistance);
        taxi1.payChecking();
        System.out.println(taxi1.payCheck);
        System.out.println("--------------10번------------");
        taxi1.setOil(-20);
        System.out.println("--------------11번------------");
        System.out.println("--------------12번------------");
        System.out.println(taxi1.oil);
        taxi1.statusChecking();
        System.out.println(taxi1.status);
        System.out.println(taxi1.money);
        System.out.println("--------------13번------------");
    }
}

